### ISSUE TITLE
Меню разваливается у правого края

### ISSUE THREAD

**Issue by dustyo-O** [h2p4x8/hj-28-h2p4x8#4]
Если его туда перетащить, менять режимы, после загрузки картинки и т.п.

**Comment by h2p4x8** [comment]
готово

**Comment by dustyo-O** [comment]
сейчас оно все еще разваливается, хотя ненадолго. Надо сделать так, чтобы даже ненадолго не разлеталось

**Comment by h2p4x8** [comment]
++
