### ISSUE TITLE
При перезагрузке стартовой страницы интерфейс мигает

### ISSUE THREAD

**Issue by dustyo-O** [h2p4x8/hj-28-h2p4x8#7]
Судя по всему, ты в js устанавливаешь стартовое состояние интерфейса. Следует просто в html/css сразу выставить правильное состояние, тогда мигать не будет, а из js оторвать инициализацию

https://monosnap.com/file/ES52SGmnXPRggqtukurrr6oWYaEJCU

**Comment by h2p4x8** [comment]
исправлено
